#!/bin/bash

# Ideas taken from
# https://github.com/cmulk/wireguard-docker
# https://github.com/denisix/wireguard

init() {
	if [ ! -f /etc/wireguard/wg0.conf ]; then
        echo "$(date): init"
		wg genkey | tee /etc/wireguard/wg0.key | wg pubkey > /etc/wireguard/wg0.pub
		SERV_KEY=`cat /etc/wireguard/wg0.key`
		cat > /etc/wireguard/wg0.conf << EOF
[Interface]
Address = 192.168.20.1/24
ListenPort = 48651
PrivateKey = $SERV_KEY
EOF
	chmod 600 /etc/wireguard/*
	fi
}

wg_up() {
    echo "$(date): wg_up"
    wg-quick up wg0
    if [ $? -eq 0 ]; then 
        wg && iptables -w -t nat -A POSTROUTING -o eth0 -j MASQUERADE
    fi
}

wg_down() {
    echo "$(date): wg_down"
    wg-quick down wg0
    iptables -w -t nat -D POSTROUTING -o eth0 -j MASQUERADE
}

init
wg_up

finish() {
    echo "$(date): finish"
    wg_down
    exit 0
}

trap finish TERM INT QUIT

# '$!' is the process ID of the job most recently placed into the background
sleep infinity & wait $!
