# https://github.com/marketplace/actions/hadolint-action
# https://docs.docker.com/ci-cd/github-actions/
# https://github.com/MaastrichtU-IDS/get-started-with-docker/blob/main/.github/workflows/publish-docker.yml
# https://pet2cattle.com/2021/09/build-multiarch-container-github-action
# https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

name: Build

env:
  IMAGE_NAME: wireguard-fedora

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
      - "start-wg"
  schedule:
    - cron: "19 7 * * 5"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: hadolint
        uses: hadolint/hadolint-action@v1.6.0

  push:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Image name
        id: imagename
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          echo "::set-output name=tags::$IMAGE_ID"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.imagename.outputs.tags }}
          platforms: linux/arm/v7
          pull: true
          push: true
